name: wemotions
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  flutter_staggered_animations: ^1.1.1 # For animations
  image_picker: ^0.8.4+8
  http: ^0.13.4
  cloudinary_dart: ^0.0.11
  cloudinary_api: ^1.0.0
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  lottie: ^1.0.1
  razorpay_flutter: ^1.3.0
  cloudinary_url_gen: ^0.10.0
  flutter_speed_dial: ^4.0.1
  cloud_firestore: ^4.14.0
  intl: ^0.19.0
  video_player: ^2.3.0
  cloudinary_public: ^0.23.1
  timeago: ^3.7.0
  flutter_sound: ^9.6.0
  record: ^4.4.4
  firebase_storage: ^11.0.0
  audioplayers: ^6.1.0
  firebase_app_check: ^0.2.2+7
  path_provider: ^2.0.15
  swipeable_button_view: ^0.0.1
  page_transition: ^2.0.9
  google_fonts: ^4.0.4
  animate_do: ^3.3.4
  circle_nav_bar: ^2.1.0+1
  firebase_messaging: ^14.9.4
  badges: ^3.1.2
  random_avatar: ^0.0.8
  flutter_svg: ^2.0.9
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/verified_success.json
    - assets/finalize.json
