// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ6qdh7yFwmIQvl33qQyJFVj-1U1ktVRA',
    appId: '1:382038334533:web:c5d9124fe3fff92fa0172c',
    messagingSenderId: '382038334533',
    projectId: 'wemotions-1e5b2',
    authDomain: 'wemotions-1e5b2.firebaseapp.com',
    storageBucket: 'wemotions-1e5b2.appspot.com',
    measurementId: 'G-3NXE340SND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_s6RUM8UlZv-vgXVbHhH5cOHnTm8zw-A',
    appId: '1:382038334533:android:1ba03865d80bffdca0172c',
    messagingSenderId: '382038334533',
    projectId: 'wemotions-1e5b2',
    storageBucket: 'wemotions-1e5b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt2cRcQEQnY_hbzet7UkMBkLNMlwPTpU8',
    appId: '1:382038334533:ios:7767cc09dc4ebb7ca0172c',
    messagingSenderId: '382038334533',
    projectId: 'wemotions-1e5b2',
    storageBucket: 'wemotions-1e5b2.appspot.com',
    iosBundleId: 'com.example.wemotions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt2cRcQEQnY_hbzet7UkMBkLNMlwPTpU8',
    appId: '1:382038334533:ios:7767cc09dc4ebb7ca0172c',
    messagingSenderId: '382038334533',
    projectId: 'wemotions-1e5b2',
    storageBucket: 'wemotions-1e5b2.appspot.com',
    iosBundleId: 'com.example.wemotions',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ6qdh7yFwmIQvl33qQyJFVj-1U1ktVRA',
    appId: '1:382038334533:web:54bdcdb92deaf46fa0172c',
    messagingSenderId: '382038334533',
    projectId: 'wemotions-1e5b2',
    authDomain: 'wemotions-1e5b2.firebaseapp.com',
    storageBucket: 'wemotions-1e5b2.appspot.com',
    measurementId: 'G-K8MJYVNN19',
  );
}
